GET http://localhost:2000/api/hotels

###
POST http://localhost:2000/api/hotels
Content-Type: application/json

{
	"name" : "Hotle Paradise",
	"type" : "hotel",
	"city": "Bengaluru",
	"address":"somewhere",
	"distance":"500",
	"title":"Best Hotel in the City",
	"desc":"hotel description",
	"cheapestPrice":100
}

###
GET localhost:2000/api/hotels

